/* eslint-disable react-native/no-color-literals */
import { StyleSheet } from "react-native";

export const getTabStyles = (colors) =>
  StyleSheet.create({
    customTabBarWrapper: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "transparent", // eslint-disable-line react-native/no-color-literals
      elevation: 0,
    },

    globalBottomTabBarExpanded: {
      backgroundColor: colors.surface,
      borderTopColor: colors.border,
      borderTopWidth: 1,
      height: 96,
      elevation: 10,
      shadowColor: "#000", // eslint-disable-line react-native/no-color-literals
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
    },
    tabBarItem: {
      justifyContent: "center",
      alignItems: "center",
      height: "100%",
    },
    tabBarItemExpanded: {
      justifyContent: "flex-start",
      alignItems: "center",
      height: "100%",
      paddingTop: 12,
    },
    expandHandleWrapper: {
      position: "absolute",
      bottom: 60,
      width: "100%",
      alignItems: "center",
    },
    collapseHandleWrapper: {
      position: "absolute",
      bottom: 96,
      width: "100%",
      alignItems: "center",
      paddingBottom: 4,
    },

    globalBottomTabBar: {
      minHeight: 76,
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      paddingBottom: 12,
      paddingTop: 12,
      flexDirection: "row",
    },
    expandHandleContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginBottom: -1,
      zIndex: 10,
    },
    tripleArrowIconBase: {
      width: 48,
      height: 24,
      backgroundColor: colors.surface,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 4,
    },
    arrowLineTop: {
      width: 10,
      height: 2,
      backgroundColor: colors.primary,
      borderRadius: 1,
      marginBottom: 2,
    },
    arrowLineMid: {
      width: 14,
      height: 2,
      backgroundColor: colors.primary,
      borderRadius: 1,
      marginBottom: 2,
    },
    arrowLineBot: {
      width: 18,
      height: 2,
      backgroundColor: colors.primary,
      borderRadius: 1,
    },
    helperPromptText: {
      position: "absolute",
      top: -24,
      fontSize: 10,
      fontStyle: "italic",
      color: colors.textMuted,
      opacity: 0.8,
    },
    inactiveTabContainer: {
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
    },
    activeTabItemContainer: {
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
    },
    activeTabIndicatorCapsule: {
      backgroundColor: colors.successLight,
      paddingHorizontal: 20,
      paddingVertical: 6,
      borderRadius: 16,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
    },
    tabBarLabelText: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: "500",
      marginTop: 4,
      textAlign: "center",
      width: "100%",
    },
    tabBarLabelTextActive: {
      fontSize: 12,
      color: colors.successDark,
      fontWeight: "700",
      marginTop: 4,
      textAlign: "center",
      width: "100%",
    },
    vectorTabIconWrapper: {
      width: 18,
      height: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    vectorIconCalendarBase: {
      width: 15,
      height: 15,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      borderRadius: 3,
      position: "relative",
    },
    vectorIconCalendarDot: {
      width: 3,
      height: 3,
      borderRadius: 1.5,
      backgroundColor: colors.textMuted,
      position: "absolute",
      bottom: 2,
      right: 2,
    },
    vectorIconChecklistRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    vectorIconCheckmarkMini: {
      fontSize: 11,
      color: colors.successDark,
      fontWeight: "900",
    },
    vectorIconCheckLine: {
      width: 6,
      height: 2,
      backgroundColor: colors.successDark,
      borderRadius: 1,
    },
    vectorIconStatsBars: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 2,
      width: 14,
      height: 14,
    },
    vectorStatBarSingle: {
      width: 3,
      backgroundColor: colors.textMuted,
      borderRadius: 1,
    },
    vectorIconTrophyCup: {
      width: 14,
      height: 10,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      borderTopWidth: 0,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 4,
    },
    vectorIconMascotFaceSmiley: {
      width: 15,
      height: 15,
      borderRadius: 7.5,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    vectorIconMascotEyesLine: {
      flexDirection: "row",
      gap: 2,
    },
    vectorIconMascotEyeDot: {
      width: 2.5,
      height: 2.5,
      borderRadius: 1.25,
      backgroundColor: colors.textMuted,
    },
    vectorIconMascotSmileMini: {
      width: 5,
      height: 2.5,
      borderBottomWidth: 1.5,
      borderColor: colors.textMuted,
      borderBottomLeftRadius: 2.5,
      borderBottomRightRadius: 2.5,
      marginTop: 1,
    },
    dummyScreenContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    dummyScreenText: {
      fontSize: 16,
      fontWeight: "bold",
    },
  });
