import { StyleSheet } from "react-native";

export const getTabStyles = (colors) =>
  StyleSheet.create({
    globalBottomTabBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: 76,
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      paddingBottom: 12,
      flexDirection: "row",
    },
    inactiveTabContainer: {
      alignItems: "center",
      justifyContent: "center",
    },
    activeTabIndicatorCapsule: {
      backgroundColor: colors.successLight,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 100,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    tabBarLabelText: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: "500",
      marginTop: 4,
    },
    tabBarLabelTextActive: {
      fontSize: 12,
      color: colors.successDark,
      fontWeight: "700",
    },
    vectorTabIconWrapper: {
      width: 18,
      height: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    vectorIconCalendarBase: {
      width: 15,
      height: 15,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      borderRadius: 3,
      position: "relative",
    },
    vectorIconCalendarDot: {
      width: 3,
      height: 3,
      borderRadius: 1.5,
      backgroundColor: colors.textMuted,
      position: "absolute",
      bottom: 2,
      right: 2,
    },
    vectorIconChecklistRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    vectorIconCheckmarkMini: {
      fontSize: 11,
      color: colors.successDark,
      fontWeight: "900",
    },
    vectorIconCheckLine: {
      width: 6,
      height: 2,
      backgroundColor: colors.successDark,
      borderRadius: 1,
    },
    vectorIconStatsBars: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 2,
      width: 14,
      height: 14,
    },
    vectorStatBarSingle: {
      width: 3,
      backgroundColor: colors.textMuted,
      borderRadius: 1,
    },
    vectorIconTrophyCup: {
      width: 14,
      height: 10,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      borderTopWidth: 0,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 4,
    },
    vectorIconMascotFaceSmiley: {
      width: 15,
      height: 15,
      borderRadius: 7.5,
      borderWidth: 1.8,
      borderColor: colors.textMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    vectorIconMascotEyesLine: {
      flexDirection: "row",
      gap: 2,
    },
    vectorIconMascotEyeDot: {
      width: 2.5,
      height: 2.5,
      borderRadius: 1.25,
      backgroundColor: colors.textMuted,
    },
    vectorIconMascotSmileMini: {
      width: 5,
      height: 2.5,
      borderBottomWidth: 1.5,
      borderColor: colors.textMuted,
      borderBottomLeftRadius: 2.5,
      borderBottomRightRadius: 2.5,
      marginTop: 1,
    },
  });
