import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FBF9',
  },
  globalTopNavigationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#F9FBF9',
  },
  headerLeftArrowButton: {
    paddingRight: 8,
  },
  headerArrowSymbol: {
    fontSize: 22,
    color: '#2D4A3E',
    fontWeight: '600',
  },
  headerMainTitleText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2D4A3E',
    flex: 1,
    marginLeft: 12,
  },
  headerRightActionGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerActionIconBtn: {
    padding: 4,
  },
  headerPlusIconSymbol: {
    fontSize: 24,
    color: '#2D4A3E',
    fontWeight: '400',
  },
  headerArchiveIconSymbol: {
    fontSize: 20,
    color: '#2D4A3E',
    fontWeight: '700',
  },
  headerStatePopoverMenu: {
    position: 'absolute',
    top: 32,
    right: 0,
    width: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    zIndex: 10000,
  },
  headerMenuPopoverItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  headerMenuPopoverText: {
    fontSize: 16,
    color: '#334155',
  },
  topFilterBarContainer: {
    paddingVertical: 8,
    marginBottom: 8,
  },
  filterBarScrollInner: {
    paddingHorizontal: 20,
    gap: 8,
  },
  filterChipButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 100,
    backgroundColor: '#EAEAEA',
  },
  filterChipButtonActive: {
    backgroundColor: '#2D4A3E',
  },
  filterChipText: {
    fontSize: 14,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  listScrollContentBody: {
    paddingHorizontal: 20, 
    gap: 12,
    paddingBottom: 100, 
  },
  cardOuterContainer: {
    position: 'relative',
    width: '100%',
    paddingVertical: 16, 
  },
  habitCardWrapper: {
    width: '100%',
    paddingVertical: 16,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F1F3F1',
  },
  cardLeftStripe: {
    width: 5,
    height: '100%',
  },
  cardMainContentContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 16,
  },
  leftMetaContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconCircleBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#A8D5BA', 
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircleBadgePaused: {
    backgroundColor: '#E0E0E0',
  },
  cardTextGroup: {
    flex: 1,
    justifyContent: 'center',
  },
  habitTitleLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1C1C1C',
    marginBottom: 4,
  },
  textMuted: {
    color: '#9E9E9E',
    textDecorationLine: 'line-through',
  },
  cardBadgesRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 4,
  },
  miniMetaBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 100,
  },
  miniMetaBadgeText: {
    fontSize: 12,
    fontWeight: '500',
  },
  priorityCapsuleRow: {
    flexDirection: 'row',
  },
  figmaPriorityCapsuleBase: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 100,
  },
  figmaPriorityCapsuleText: {
    fontSize: 11,
    fontWeight: '600',
  },
  cardRightActionBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginLeft: 4,
  },
  statusCapsule: {
    width: 72, 
    height: 28, 
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusCapsuleActive: {
    backgroundColor: '#C2E7D9',
  },
  statusCapsulePaused: {
    backgroundColor: '#FDE8BB',
  },
  statusCapsuleArchived: {
    backgroundColor: '#EAEAEA',
  },
  statusCapsuleText: {
    fontSize: 12,
    fontWeight: '600',
  },
  statusTextActive: {
    color: '#1E4631',
  },
  statusTextPaused: {
    color: '#B76E00',
  },
  statusTextArchived: {
    color: '#5F6368',
  },
  figmaChevronRightContainer: {
    width: 8,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  figmaChevronLineTop: {
    width: 6,
    height: 2,
    backgroundColor: '#5F6368',
    transform: [{ rotate: '45deg' }],
    marginBottom: 2,
  },
  figmaChevronLineBottom: {
    width: 6,
    height: 2,
    backgroundColor: '#5F6368',
    transform: [{ rotate: '-45deg' }],
  },
  cardDropdownListMenu: {
    position: 'absolute',
    top: 68, 
    right: 28,
    width: 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    zIndex: 9999,
  },
  cardDropdownOptionItem: {
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardDropdownOptionText: {
    fontSize: 12,
    color: '#2D4A3E',
    fontWeight: '600',
  },
  floatingActionButton: {
    position: 'absolute',
    bottom: 96, 
    right: 24, 
    width: 56, 
    height: 56,
    borderRadius: 28,
    backgroundColor: '#8FDAB5', 
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2D4A3E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
    zIndex: 999, 
  },
  fabPlusSignHorizontal: {
    width: 20,
    height: 3,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
  },
  fabPlusSignVertical: {
    width: 3,
    height: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    position: 'absolute',
  },
  iconDropletBase: {
    alignItems: 'center',
  },
  iconDropletTip: {
    width: 0,
    height: 0,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#2D4A3E',
  },
  iconDropletRound: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2D4A3E',
    marginTop: -2,
  },
  iconBookContainer: {
    flexDirection: 'row',
    gap: 1,
  },
  iconBookLeftPage: {
    width: 6,
    height: 11,
    borderWidth: 1.5,
    borderColor: '#2D4A3E',
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
  },
  iconBookRightPage: {
    width: 6,
    height: 11,
    borderWidth: 1.5,
    borderColor: '#2D4A3E',
    borderTopRightRadius: 2,
    borderBottomRightRadius: 2,
  },
  iconMeditationContainer: {
    alignItems: 'center',
  },
  iconMeditationHead: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#2D4A3E',
    marginBottom: 1,
  },
  iconMeditationTorso: {
    width: 9,
    height: 6,
    borderWidth: 1.5,
    borderColor: '#2D4A3E',
    borderBottomWidth: 0,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  iconMeditationBaseLine: {
    width: 12,
    height: 1.5,
    backgroundColor: '#2D4A3E',
  },
  iconWorkBriefcase: {
    width: 14,
    height: 11,
    borderWidth: 1.6,
    borderColor: '#2D4A3E',
    borderRadius: 2,
    position: 'relative',
    marginTop: 2,
  },
  iconBriefcaseHandle: {
    width: 6,
    height: 4,
    borderWidth: 1.6,
    borderColor: '#2D4A3E',
    borderBottomWidth: 0,
    position: 'absolute',
    top: -4,
    left: 2,
    borderTopLeftRadius: 1.5,
    borderTopRightRadius: 1.5,
  },
  iconStarDefaultText: {
    fontSize: 14,
    color: '#2D4A3E',
  },
  loadingCenterWheel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});