/* eslint-disable react-native/no-color-literals, no-dupe-keys, react-native/no-inline-styles, i18next/no-literal-string, react-native-a11y/no-nested-touchables */
import { StyleSheet, Platform } from "react-native";

export const getStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    flexContainer: {
      flex: 1,
      position: "relative",
    },
    globalTopNavigationHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.background,
    },
    headerLeftArrowButton: {
      paddingRight: 8,
    },
    headerArrowSymbol: {
      fontSize: 22,
      color: colors.primary,
      fontWeight: "600",
    },
    headerMainTitleText: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.primary,
      flex: 1,
      marginLeft: 12,
    },
    headerRightActionGroup: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
    },
    headerActionIconBtn: {
      padding: 4,
    },
    headerIconButton: {
      padding: 4,
    },
    langMenuWrapper: { position: "relative" },
    themeMenuWrapper: { position: "relative" },
    relativeWrapper: { position: "relative" },
    headerPlusIconSymbol: {
      fontSize: 24,
      color: colors.primary,
      fontWeight: "400",
    },
    headerArchiveIconSymbol: {
      fontSize: 20,
      color: colors.primary,
      fontWeight: "700",
    },
    headerStatePopoverMenu: {
      position: "absolute",
      right: 0,
      top: 32,
      width: 140,
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border,
      zIndex: 10000,
    },
    headerMenuPopoverItem: {
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    headerMenuPopoverText: {
      fontSize: 12,
      color: colors.textSecondary,
    },

    topFilterBarContainer: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "flex-end", 
      paddingHorizontal: 20,
      paddingVertical: 0,
      marginBottom: 2,
      position: "relative",
    },
    filterTriggerRowBtn: {
      flexDirection: "row",       
      alignItems: "center",       
      paddingVertical: 2,         
      paddingHorizontal: 6,
      borderRadius: 8,
    },
    filterTriggerText: {
      marginLeft: 6,              
      color: colors.primary,
      fontWeight: "600",
      fontSize: 14,
    },
    filterStandalonePopoverMenu: {
      position: "absolute",
      right: 20,
      top: 28,
      width: 140,
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border,
      zIndex: 10000,
    },

    listScrollContentBody: {
      paddingHorizontal: 20,
      gap: 12,
      paddingBottom: 120,
    },
    cardOuterContainer: {
      position: "relative",
      width: "100%",
      paddingVertical: 4,
    },
    habitCardWrapper: {
      width: "100%",
      paddingVertical: 16,
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 32,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.surfaceMuted,
    },
    cardLeftStripe: {
      width: 5,
      height: "100%",
    },
    cardMainContentContainer: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: 12,
      paddingRight: 16,
    },
    leftMetaContainer: {
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    iconCircleBadge: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    iconCircleBadgePaused: {
      backgroundColor: colors.border,
    },
    cardTextGroup: {
      flex: 1,
      justifyContent: "center",
    },
    habitTitleLabel: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 4,
    },
    textMuted: {
      color: colors.textDisabled,
      textDecorationLine: "line-through",
    },

    cardTagsGrid: {
      flexDirection: "column",
      gap: 6,                       
      marginTop: 2,
    },
    cardTagsTopGroup: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,                       
    },
    cardTagsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },

    miniMetaBadge: {
      paddingHorizontal: 10,        
      paddingVertical: 2,           
      borderRadius: 100,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "flex-start",     
    },
    miniMetaBadgeText: {
      fontSize: 12,                 
      lineHeight: 16,
      fontWeight: "500",
      textAlign: "center",
    },
    figmaPriorityCapsuleBase: {
      paddingHorizontal: 10,
      paddingVertical: 2,
      borderRadius: 100,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "flex-start",     
    },
    figmaPriorityCapsuleText: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600",
      textAlign: "center",
    },

    cardRightActionBlock: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginLeft: 4,
    },
    
    // --- TĂNG SIZE NÚT ACTIVE / CAPSULE TRẠNG THÁI CHUẨN ---
    statusCapsule: {
      paddingHorizontal: 12,        // Tăng padding ngang để cân đối với text lớn hơn
      height: 28,                   // Tăng chiều cao lên 1 size (Từ 24 lên 28)
      borderRadius: 100,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: "auto",
    },
    statusCapsuleActive: {
      backgroundColor: colors.successLight,
    },
    statusCapsulePaused: {
      backgroundColor: colors.warningLight,
    },
    statusCapsuleArchived: {
      backgroundColor: colors.border,
    },
    statusCapsuleText: {
      fontSize: 12,                 // Tăng kích thước chữ lên 1 size (Từ 11 lên 12)
      fontWeight: "600",
      textAlign: "center",
    },
    statusTextActive: {
      color: colors.successDark,
    },
    statusTextPaused: {
      color: colors.warningDark,
    },
    statusTextArchived: {
      color: colors.textMuted,
    },
    figmaChevronRightContainer: {
      width: 8,
      height: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    figmaChevronLineTop: {
      width: 6,
      height: 2,
      backgroundColor: colors.textMuted,
      transform: [{ rotate: "45deg" }],
      marginBottom: 2,
    },
    figmaChevronLineBottom: {
      width: 6,
      height: 2,
      backgroundColor: colors.textMuted,
      transform: [{ rotate: "-45deg" }],
    },
    cardDropdownListMenu: {
      position: "absolute",
      top: 56,
      right: 28,
      minWidth: "30%",
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border,
      zIndex: 9999,
    },
    cardDropdownOptionItem: {
      height: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    cardDropdownOptionText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: "600",
    },
    iconDropletBase: { alignItems: "center" },
    iconDropletTip: {
      width: 0,
      height: 0,
      borderLeftWidth: 4,
      borderRightWidth: 4,
      borderBottomWidth: 6,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderBottomColor: colors.primary,
    },
    iconDropletRound: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.primary,
      marginTop: -2,
    },
    iconBookContainer: { flexDirection: "row", gap: 1 },
    iconBookLeftPage: {
      width: 6,
      height: 11,
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderTopLeftRadius: 2,
      borderBottomLeftRadius: 2,
    },
    iconBookRightPage: {
      width: 6,
      height: 11,
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderTopRightRadius: 2,
      borderBottomRightRadius: 2,
    },
    iconMeditationContainer: { alignItems: "center" },
    iconMeditationHead: {
      width: 5,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.primary,
      marginBottom: 1,
    },
    iconMeditationTorso: {
      width: 9,
      height: 6,
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderBottomWidth: 0,
      borderTopLeftRadius: 3,
      borderTopRightRadius: 3,
    },
    iconMeditationBaseLine: {
      width: 12,
      height: 1.5,
      backgroundColor: colors.primary,
    },
    iconWorkBriefcase: {
      width: 14,
      height: 11,
      borderWidth: 1.6,
      borderColor: colors.primary,
      borderRadius: 2,
      position: "relative",
      marginTop: 2,
    },
    iconBriefcaseHandle: {
      width: 6,
      height: 4,
      borderWidth: 1.6,
      borderColor: colors.primary,
      borderBottomWidth: 0,
      position: "absolute",
      top: -4,
      left: 2,
      borderTopLeftRadius: 1.5,
      borderTopRightRadius: 1.5,
    },
    iconStarDefaultText: {
      fontSize: 14,
      color: colors.primary,
    },
    loadingCenterWheel: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    floatingActionButton: {
      position: "absolute",
      right: 24,
      bottom: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      elevation: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.27,
      shadowRadius: 4.65,
      zIndex: 99999,
    },
    fabPlusSignHorizontal: {
      width: 20,
      height: 2,
      backgroundColor: colors.onPrimary,
      position: "absolute",
    },
    fabPlusSignVertical: {
      width: 2,
      height: 20,
      backgroundColor: colors.onPrimary,
      position: "absolute",
    },
  });