/* eslint-disable react-native/no-color-literals, no-dupe-keys, react-native/no-inline-styles, i18next/no-literal-string, react-native-a11y/no-nested-touchables */
import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const getStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#FAFBFB",
    },
    topHeaderContainer: {
      paddingVertical: 16,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: "#F1F3F2",
    },
    headerCancelText: {
      fontSize: 16,
      color: "#3D6A52",
      fontWeight: "600",
    },
    headerDeleteText: {
      fontSize: 16,
      color: "#EF4444",
      fontWeight: "600",
    },
    headerTitleText: {
      fontSize: 18,
      fontWeight: "700",
      color: "#111827",
    },
    headerSaveCapsuleButton: {
      backgroundColor: "#3D6A52",
      paddingHorizontal: 22,
      paddingVertical: 8,
      borderRadius: 100,
    },
    headerSaveCapsuleText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.surface,
    },
    scrollContainer: {
      padding: 24,
      paddingBottom: 40,
    },
    mascotSpeechSection: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 28,
    },
    mascotRoundAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#A8D3BE",
      justifyContent: "center",
      alignItems: "center",
    },
    mascotMiniFace: {
      width: 20,
      height: 20,
      justifyContent: "center",
      alignItems: "center",
    },
    mascotMiniEyesRow: {
      flexDirection: "row",
      gap: 4,
      marginBottom: 3,
    },
    mascotMiniEye: {
      width: 3,
      height: 3,
      borderRadius: 1.5,
      backgroundColor: colors.primary,
    },
    mascotMiniSmile: {
      width: 10,
      height: 5,
      borderBottomWidth: 1.5,
      borderColor: colors.primary,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
    },
    mascotBubbleCloud: {
      flex: 1,
      backgroundColor: "#F5F7F6",
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderWidth: 1,
      borderColor: "#E9EBEA",
    },
    mascotBubbleText: {
      fontSize: 14,
      color: "#475569",
      lineHeight: 20,
      fontWeight: "500",
    },
    formGroup: {
      marginBottom: 24,
    },
    formInlineRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 24,
    },
    labelSubGroup: {
      gap: 2,
    },
    formLabelText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textSecondary,
      marginBottom: 4,
    },
    subHintTextText: {
      fontSize: 12,
      color: "#94A3B8",
    },
    customDaysValuePreviewText: {
      fontSize: 12,
      color: "#3D6A52",
      fontWeight: "600",
      textDecorationLine: "underline",
    },
    pencilInputWrapper: {
      width: width - 48,
      paddingVertical: 16,
      backgroundColor: "#FBFDFD",
      borderRadius: 24,
      borderWidth: 1,
      borderColor: "#E2E8F0",
      paddingHorizontal: 20,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    inputFieldDisabled: {
      backgroundColor: "#F1F3F2",
      borderColor: "#E9EBEA",
      opacity: 0.8,
    },
    mainInputField: {
      flex: 1,
      fontSize: 15,
      color: "#111827",
      fontWeight: "500",
      paddingVertical: 0,
      marginRight: 10,
    },
    figmaPencilVectorIcon: {
      width: 16,
      height: 16,
      transform: [{ rotate: "-45deg" }],
      alignItems: "center",
    },
    pencilLeadTip: {
      width: 0,
      height: 0,
      borderLeftWidth: 3,
      borderRightWidth: 3,
      borderBottomWidth: 4,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderBottomColor: "#64748B",
    },
    pencilLongBody: {
      width: 5,
      height: 12,
      backgroundColor: "#64748B",
      borderRadius: 0.5,
    },
    categoryChipsMatrix: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    figmaCategoryChip: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 100,
      backgroundColor: "#EEF1F0",
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 1,
      maxWidth: "45%",
    },
    figmaCategoryChipActive: {
      backgroundColor: "#3D6A52",
    },
    figmaCategoryChipText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#475569",
    },
    figmaCategoryChipTextActive: {
      color: colors.surface,
    },
    capsuleToggleContainer: {
      flexDirection: "row",
      backgroundColor: "#EEF1F0",
      borderRadius: 20,
      padding: 4,
    },
    capsuleToggleButton: {
      paddingHorizontal: 18,
      height: 32,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 1,
    },
    capsuleToggleButtonActive: {
      backgroundColor: "#3D6A52",
    },
    capsuleToggleText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#475569",
    },
    capsuleToggleTextActive: {
      color: colors.surface,
    },
    figmaCounterPillContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#EEF1F0",
      borderRadius: 24,
      padding: 4,
      gap: 4,
    },
    counterCircleBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "#E1E5E3",
      justifyContent: "center",
      alignItems: "center",
    },
    counterBtnSymbol: {
      fontSize: 16,
      fontWeight: "700",
      color: "#475569",
    },
    counterValueInputNode: {
      width: 44,
      textAlign: "center",
      fontSize: 18,
      fontWeight: "700",
      color: "#111827",
      padding: 0,
    },
    priorityFlexibleRow: {
      flexDirection: "row",
      gap: 10,
    },
    priorityBlockButton: {
      flex: 1,
      height: 48,
      borderRadius: 24,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1.5,
    },
    priorityBlockButtonInactive: {
      backgroundColor: "#F8FAFC",
      borderColor: colors.surfaceMuted,
    },
    lowPriorityActiveBorder: {
      backgroundColor: colors.priorityLowBg,
      borderColor: colors.priorityLowStripe,
    },
    mediumPriorityActiveBorder: {
      backgroundColor: "#FFFDF0",
      borderColor: "#EAB308",
    },
    highPriorityActiveBorder: {
      backgroundColor: "#FEF2F2",
      borderColor: "#EF4444",
    },
    priorityBlockText: {
      fontSize: 14,
      fontWeight: "600",
    },
    priorityBlockTextInactive: {
      color: "#475569",
    },
    priorityBlockTextActive: {
      color: "#1E293B",
      fontWeight: "700",
    },
    bottomLightGreenBanner: {
      width: "100%",
      paddingVertical: 24,
      borderRadius: 32,
      backgroundColor: "#E8F2EE",
      marginTop: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    proTipFloatingBadge: {
      backgroundColor: colors.surface,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    proTipTextContent: {
      fontSize: 13,
      fontWeight: "600",
      color: "#3D6A52",
    },

    modalOverlayBackground: {
      flex: 1,
      backgroundColor: "rgba(15, 23, 42, 0.4)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContentCardBox: {
      width: width - 56,
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 10,
    },
    modalHeaderTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: "#111827",
      marginBottom: 8,
      textAlign: "center",
    },
    modalSubDescription: {
      fontSize: 14,
      color: "#64748B",
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 20,
    },
    modalDaysListWrapper: {
      gap: 4,
      marginBottom: 24,
    },
    modalDayRowItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      height: 46,
      paddingHorizontal: 16,
      borderRadius: 14,
      backgroundColor: "#F8FAFC",
    },
    modalDayRowItemActive: {
      backgroundColor: "#E8F2EE",
    },
    modalDayRowText: {
      fontSize: 15,
      fontWeight: "600",
      color: "#475569",
    },
    modalDayRowTextActive: {
      color: "#3D6A52",
      fontWeight: "700",
    },
    checkmarkIconSymbol: {
      fontSize: 16,
      fontWeight: "700",
      color: "#3D6A52",
    },
    modalDoneActionButton: {
      backgroundColor: "#3D6A52",
      paddingVertical: 12,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
    },
    modalDoneButtonText: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.surface,
    },
    modalOverlayBackground: {
      flex: 1,
      backgroundColor: "rgba(15, 23, 42, 0.3)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContentCardBox: {
      width: "90%",
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 24,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    modalHeaderTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: "#111827",
      marginBottom: 4,
    },
    modalSubDescription: {
      fontSize: 13,
      color: "#64748B",
      marginBottom: 20,
    },
    modalDaysHorizontalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 24,
    },
    ratioDayCircleButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.surfaceMuted,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#E2E8F0",
    },
    ratioDayCircleButtonActive: {
      backgroundColor: "#3D6A52",
      borderColor: "#3D6A52",
    },
    ratioDayCircleText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#64748B",
    },
    ratioDayCircleTextActive: {
      color: colors.surface,
      fontWeight: "700",
    },
    modalDoneActionButton: {
      backgroundColor: "#3D6A52",
      width: "100%",
      height: 48,
      borderRadius: 24,
      justifyContent: "center",
      alignItems: "center",
    },
    modalDoneButtonText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.surface,
    },
  });
